GET http://localhost:3000/api/v1/usuarios HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcxMDI0MjgsImV4cCI6MTcwNzEwNjAyOH0.n5C12Cx3U6cTFElKQHrjAfn1RP5FVOSNdVZ-MFsWBfs

###
GET http://localhost:3000/api/v1/usuarios/116a6ebe-9d7f-4ea4-9af5-a5b2ca8da3fe HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcwOTg0OTMsImV4cCI6MTcwNzEwMjA5M30.5fXhVVe_03XVpAD8SWdsOi8r7739cyPIvEvTebWq7eQ

###
GET http://localhost:3000/api/v1/token/verify HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcwNzg4MTEsImV4cCI6MTcwNzA4MjQxMX0.cMd9kaRvmsE1Vh6ftxf1TvQzr9dYWsgDi1NaS6dB4ZI

###
POST http://localhost:3000/api/v1/usuarios HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcwNzE4NjQsImV4cCI6MTcwNzA3NTQ2NH0.6jd6U6WGa86flMCCOZUWe5-TrMWIQnfdHzoTfb2fiMg

{
    "name": "Francisco",
    "email": "francisco@gmail.com",
    "password": "abcde12345!"
}

###
PATCH http://localhost:3000/api/v1/usuarios/116a6ebe-9d7f-4ea4-9af5-a5b2ca8da3fe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcxMDI0MjgsImV4cCI6MTcwNzEwNjAyOH0.n5C12Cx3U6cTFElKQHrjAfn1RP5FVOSNdVZ-MFsWBfs

{
    "name": "Brandon",
    "email": "brandon@gmail.com"
}

###
POST http://localhost:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "email": "francisco@gmail.com",
    "password": "abcde12345!"
}

###
DELETE http://localhost:3000/api/v1/usuarios/d6f847b1-f5c0-4d47-ac44-65aedc48ef6f HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTZhNmViZS05ZDdmLTRlYTQtOWFmNS1hNWIyY2E4ZGEzZmUiLCJpYXQiOjE3MDcwOTY1MzAsImV4cCI6MTcwNzEwMDEzMH0.kUmBu-ik0Ju39SBjZwZQwCUoNiN5WLmMk0jbdBuPp-E